language: rust
sudo: false
dist: trusty
rust: nightly
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || travis_wait cargo install rustfmt -j 1 --verbose --vers 0.7.1
- rustfmt --version
- c++ --version
script:
- travis_wait cargo build -j 1 --verbose
- cargo fmt --verbose -- --write-mode=diff
- cargo test --verbose
