language: rust
sudo: false
cache: cargo
rust: nightly
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt --vers 0.7.1
- rustfmt --version
- which c++
- c++ --version
- ls -l /usr/bin/c++* /usr/bin/g++*
- echo $PATH
- env
script:
- cargo build
- cargo fmt -- --write-mode=diff
- cargo test
