language: rust
sudo: false
cache: cargo
rust: nightly
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt --vers 0.7.1
- rustfmt --version
- export CC="/usr/bin/g++-5"
- '"$CC" --version'
script:
- cargo build --verbose
- cargo fmt --verbose -- --write-mode=diff
- cargo test --verbose
