[package]
name = "conrod-testing"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]
description = "Personal testbed of conrod."

repository = "https://github.com/daboross/conrod-testing"

readme = "README.md"

keywords = []
categories = ["games"]
license = "MIT"

[lib]
name = "conrod_testing"
path = "src/rust/lib.rs"

[dependencies]
rand = "0.3"
glium = "0.16"
glutin = "0.7"
rusttype = "0.2"

[dependencies.screeps-api]
path = "../screeps-api/"

[dependencies.conrod]
version = "0.51"
features = ["glium", "winit"]

[[bin]]
name = "testbed"
doc = false
